# Generated by Django 6.0.1 on 2026-04-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articolo_options_alter_giornalista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
